/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmBasicDataType implements Serializable {

    private static final long serialVersionUID = -354120406;

    private String  dataId;
    private String  dataName;
    private Integer dataType;
    private String  memo;

    public TmBasicDataType() {}

    public TmBasicDataType(TmBasicDataType value) {
        this.dataId = value.dataId;
        this.dataName = value.dataName;
        this.dataType = value.dataType;
        this.memo = value.memo;
    }

    public TmBasicDataType(
        String  dataId,
        String  dataName,
        Integer dataType,
        String  memo
    ) {
        this.dataId = dataId;
        this.dataName = dataName;
        this.dataType = dataType;
        this.memo = memo;
    }

    public String getDataId() {
        return this.dataId;
    }

    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    public String getDataName() {
        return this.dataName;
    }

    public void setDataName(String dataName) {
        this.dataName = dataName;
    }

    public Integer getDataType() {
        return this.dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmBasicDataType (");

        sb.append(dataId);
        sb.append(", ").append(dataName);
        sb.append(", ").append(dataType);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
