/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDistributeValue implements Serializable {

    private static final long serialVersionUID = 109823990;

    private Integer eleIndex;
    private Integer mineralIndex;
    private Integer meltIndex;
    private Double  distributeValue;

    public TmDistributeValue() {}

    public TmDistributeValue(TmDistributeValue value) {
        this.eleIndex = value.eleIndex;
        this.mineralIndex = value.mineralIndex;
        this.meltIndex = value.meltIndex;
        this.distributeValue = value.distributeValue;
    }

    public TmDistributeValue(
        Integer eleIndex,
        Integer mineralIndex,
        Integer meltIndex,
        Double  distributeValue
    ) {
        this.eleIndex = eleIndex;
        this.mineralIndex = mineralIndex;
        this.meltIndex = meltIndex;
        this.distributeValue = distributeValue;
    }

    public Integer getEleIndex() {
        return this.eleIndex;
    }

    public void setEleIndex(Integer eleIndex) {
        this.eleIndex = eleIndex;
    }

    public Integer getMineralIndex() {
        return this.mineralIndex;
    }

    public void setMineralIndex(Integer mineralIndex) {
        this.mineralIndex = mineralIndex;
    }

    public Integer getMeltIndex() {
        return this.meltIndex;
    }

    public void setMeltIndex(Integer meltIndex) {
        this.meltIndex = meltIndex;
    }

    public Double getDistributeValue() {
        return this.distributeValue;
    }

    public void setDistributeValue(Double distributeValue) {
        this.distributeValue = distributeValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmDistributeValue (");

        sb.append(eleIndex);
        sb.append(", ").append(mineralIndex);
        sb.append(", ").append(meltIndex);
        sb.append(", ").append(distributeValue);

        sb.append(")");
        return sb.toString();
    }
}
