/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDistributeValue implements Serializable {

    private static final long serialVersionUID = 179476119;

    private String eleName;
    private String mineralId;
    private String meltType;
    private Double distributeValue;

    public TmDistributeValue() {}

    public TmDistributeValue(TmDistributeValue value) {
        this.eleName = value.eleName;
        this.mineralId = value.mineralId;
        this.meltType = value.meltType;
        this.distributeValue = value.distributeValue;
    }

    public TmDistributeValue(
        String eleName,
        String mineralId,
        String meltType,
        Double distributeValue
    ) {
        this.eleName = eleName;
        this.mineralId = mineralId;
        this.meltType = meltType;
        this.distributeValue = distributeValue;
    }

    public String getEleName() {
        return this.eleName;
    }

    public void setEleName(String eleName) {
        this.eleName = eleName;
    }

    public String getMineralId() {
        return this.mineralId;
    }

    public void setMineralId(String mineralId) {
        this.mineralId = mineralId;
    }

    public String getMeltType() {
        return this.meltType;
    }

    public void setMeltType(String meltType) {
        this.meltType = meltType;
    }

    public Double getDistributeValue() {
        return this.distributeValue;
    }

    public void setDistributeValue(Double distributeValue) {
        this.distributeValue = distributeValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmDistributeValue (");

        sb.append(eleName);
        sb.append(", ").append(mineralId);
        sb.append(", ").append(meltType);
        sb.append(", ").append(distributeValue);

        sb.append(")");
        return sb.toString();
    }
}
