/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmElement implements Serializable {

    private static final long serialVersionUID = 761902511;

    private Integer index;
    private String  elementName;
    private String  memo;

    public TmElement() {}

    public TmElement(TmElement value) {
        this.index = value.index;
        this.elementName = value.elementName;
        this.memo = value.memo;
    }

    public TmElement(
        Integer index,
        String  elementName,
        String  memo
    ) {
        this.index = index;
        this.elementName = elementName;
        this.memo = memo;
    }

    public Integer getIndex() {
        return this.index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getElementName() {
        return this.elementName;
    }

    public void setElementName(String elementName) {
        this.elementName = elementName;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmElement (");

        sb.append(index);
        sb.append(", ").append(elementName);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
