/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmExpr implements Serializable {

    private static final long serialVersionUID = 226077293;

    private String  exprId;
    private String  exprName;
    private String  exprClassPath;
    private Integer exprType;
    private String  memo;

    public TmExpr() {}

    public TmExpr(TmExpr value) {
        this.exprId = value.exprId;
        this.exprName = value.exprName;
        this.exprClassPath = value.exprClassPath;
        this.exprType = value.exprType;
        this.memo = value.memo;
    }

    public TmExpr(
        String  exprId,
        String  exprName,
        String  exprClassPath,
        Integer exprType,
        String  memo
    ) {
        this.exprId = exprId;
        this.exprName = exprName;
        this.exprClassPath = exprClassPath;
        this.exprType = exprType;
        this.memo = memo;
    }

    public String getExprId() {
        return this.exprId;
    }

    public void setExprId(String exprId) {
        this.exprId = exprId;
    }

    public String getExprName() {
        return this.exprName;
    }

    public void setExprName(String exprName) {
        this.exprName = exprName;
    }

    public String getExprClassPath() {
        return this.exprClassPath;
    }

    public void setExprClassPath(String exprClassPath) {
        this.exprClassPath = exprClassPath;
    }

    public Integer getExprType() {
        return this.exprType;
    }

    public void setExprType(Integer exprType) {
        this.exprType = exprType;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmExpr (");

        sb.append(exprId);
        sb.append(", ").append(exprName);
        sb.append(", ").append(exprClassPath);
        sb.append(", ").append(exprType);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
