/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmInitialValue implements Serializable {

    private static final long serialVersionUID = 780377590;

    private String  initialId;
    private Integer eleIndex;
    private Double  initialValue;

    public TmInitialValue() {}

    public TmInitialValue(TmInitialValue value) {
        this.initialId = value.initialId;
        this.eleIndex = value.eleIndex;
        this.initialValue = value.initialValue;
    }

    public TmInitialValue(
        String  initialId,
        Integer eleIndex,
        Double  initialValue
    ) {
        this.initialId = initialId;
        this.eleIndex = eleIndex;
        this.initialValue = initialValue;
    }

    public String getInitialId() {
        return this.initialId;
    }

    public void setInitialId(String initialId) {
        this.initialId = initialId;
    }

    public Integer getEleIndex() {
        return this.eleIndex;
    }

    public void setEleIndex(Integer eleIndex) {
        this.eleIndex = eleIndex;
    }

    public Double getInitialValue() {
        return this.initialValue;
    }

    public void setInitialValue(Double initialValue) {
        this.initialValue = initialValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmInitialValue (");

        sb.append(initialId);
        sb.append(", ").append(eleIndex);
        sb.append(", ").append(initialValue);

        sb.append(")");
        return sb.toString();
    }
}
