/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmInitialType implements Serializable {

    private static final long serialVersionUID = -611833369;

    private String  initialId;
    private String  initialName;
    private Integer initialTyp;
    private String  memo;

    public TmInitialType() {}

    public TmInitialType(TmInitialType value) {
        this.initialId = value.initialId;
        this.initialName = value.initialName;
        this.initialTyp = value.initialTyp;
        this.memo = value.memo;
    }

    public TmInitialType(
        String  initialId,
        String  initialName,
        Integer initialTyp,
        String  memo
    ) {
        this.initialId = initialId;
        this.initialName = initialName;
        this.initialTyp = initialTyp;
        this.memo = memo;
    }

    public String getInitialId() {
        return this.initialId;
    }

    public void setInitialId(String initialId) {
        this.initialId = initialId;
    }

    public String getInitialName() {
        return this.initialName;
    }

    public void setInitialName(String initialName) {
        this.initialName = initialName;
    }

    public Integer getInitialTyp() {
        return this.initialTyp;
    }

    public void setInitialTyp(Integer initialTyp) {
        this.initialTyp = initialTyp;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmInitialType (");

        sb.append(initialId);
        sb.append(", ").append(initialName);
        sb.append(", ").append(initialTyp);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
