/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmLabReport implements Serializable {

    private static final long serialVersionUID = -341548668;

    private String    reportId;
    private String    userId;
    private Timestamp updTime;
    private Integer   reportScore;
    private Integer   reportTeacherStatus;
    private Integer   reportStudentStatus;

    public TmLabReport() {}

    public TmLabReport(TmLabReport value) {
        this.reportId = value.reportId;
        this.userId = value.userId;
        this.updTime = value.updTime;
        this.reportScore = value.reportScore;
        this.reportTeacherStatus = value.reportTeacherStatus;
        this.reportStudentStatus = value.reportStudentStatus;
    }

    public TmLabReport(
        String    reportId,
        String    userId,
        Timestamp updTime,
        Integer   reportScore,
        Integer   reportTeacherStatus,
        Integer   reportStudentStatus
    ) {
        this.reportId = reportId;
        this.userId = userId;
        this.updTime = updTime;
        this.reportScore = reportScore;
        this.reportTeacherStatus = reportTeacherStatus;
        this.reportStudentStatus = reportStudentStatus;
    }

    public String getReportId() {
        return this.reportId;
    }

    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Timestamp getUpdTime() {
        return this.updTime;
    }

    public void setUpdTime(Timestamp updTime) {
        this.updTime = updTime;
    }

    public Integer getReportScore() {
        return this.reportScore;
    }

    public void setReportScore(Integer reportScore) {
        this.reportScore = reportScore;
    }

    public Integer getReportTeacherStatus() {
        return this.reportTeacherStatus;
    }

    public void setReportTeacherStatus(Integer reportTeacherStatus) {
        this.reportTeacherStatus = reportTeacherStatus;
    }

    public Integer getReportStudentStatus() {
        return this.reportStudentStatus;
    }

    public void setReportStudentStatus(Integer reportStudentStatus) {
        this.reportStudentStatus = reportStudentStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmLabReport (");

        sb.append(reportId);
        sb.append(", ").append(userId);
        sb.append(", ").append(updTime);
        sb.append(", ").append(reportScore);
        sb.append(", ").append(reportTeacherStatus);
        sb.append(", ").append(reportStudentStatus);

        sb.append(")");
        return sb.toString();
    }
}
