/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMeltType implements Serializable {

    private static final long serialVersionUID = -1936305186;

    private String  meltName;
    private Integer meltType;

    public TmMeltType() {}

    public TmMeltType(TmMeltType value) {
        this.meltName = value.meltName;
        this.meltType = value.meltType;
    }

    public TmMeltType(
        String  meltName,
        Integer meltType
    ) {
        this.meltName = meltName;
        this.meltType = meltType;
    }

    public String getMeltName() {
        return this.meltName;
    }

    public void setMeltName(String meltName) {
        this.meltName = meltName;
    }

    public Integer getMeltType() {
        return this.meltType;
    }

    public void setMeltType(Integer meltType) {
        this.meltType = meltType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmMeltType (");

        sb.append(meltName);
        sb.append(", ").append(meltType);

        sb.append(")");
        return sb.toString();
    }
}
