/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMeltType implements Serializable {

    private static final long serialVersionUID = -258248175;

    private Integer index;
    private String  meltName;
    private String  memo;

    public TmMeltType() {}

    public TmMeltType(TmMeltType value) {
        this.index = value.index;
        this.meltName = value.meltName;
        this.memo = value.memo;
    }

    public TmMeltType(
        Integer index,
        String  meltName,
        String  memo
    ) {
        this.index = index;
        this.meltName = meltName;
        this.memo = memo;
    }

    public Integer getIndex() {
        return this.index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getMeltName() {
        return this.meltName;
    }

    public void setMeltName(String meltName) {
        this.meltName = meltName;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmMeltType (");

        sb.append(index);
        sb.append(", ").append(meltName);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
