/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMixType implements Serializable {

    private static final long serialVersionUID = 876190379;

    private String mixId;
    private String mixName;
    private String mixMemo;

    public TmMixType() {}

    public TmMixType(TmMixType value) {
        this.mixId = value.mixId;
        this.mixName = value.mixName;
        this.mixMemo = value.mixMemo;
    }

    public TmMixType(
        String mixId,
        String mixName,
        String mixMemo
    ) {
        this.mixId = mixId;
        this.mixName = mixName;
        this.mixMemo = mixMemo;
    }

    public String getMixId() {
        return this.mixId;
    }

    public void setMixId(String mixId) {
        this.mixId = mixId;
    }

    public String getMixName() {
        return this.mixName;
    }

    public void setMixName(String mixName) {
        this.mixName = mixName;
    }

    public String getMixMemo() {
        return this.mixMemo;
    }

    public void setMixMemo(String mixMemo) {
        this.mixMemo = mixMemo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmMixType (");

        sb.append(mixId);
        sb.append(", ").append(mixName);
        sb.append(", ").append(mixMemo);

        sb.append(")");
        return sb.toString();
    }
}
