/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMineral implements Serializable {

    private static final long serialVersionUID = -1529644689;

    private String mineralId;
    private String mineralName;
    private String memo;

    public TmMineral() {}

    public TmMineral(TmMineral value) {
        this.mineralId = value.mineralId;
        this.mineralName = value.mineralName;
        this.memo = value.memo;
    }

    public TmMineral(
        String mineralId,
        String mineralName,
        String memo
    ) {
        this.mineralId = mineralId;
        this.mineralName = mineralName;
        this.memo = memo;
    }

    public String getMineralId() {
        return this.mineralId;
    }

    public void setMineralId(String mineralId) {
        this.mineralId = mineralId;
    }

    public String getMineralName() {
        return this.mineralName;
    }

    public void setMineralName(String mineralName) {
        this.mineralName = mineralName;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmMineral (");

        sb.append(mineralId);
        sb.append(", ").append(mineralName);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
