/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMixValue implements Serializable {

    private static final long serialVersionUID = -967953738;

    private String eleName;
    private String mixId;
    private Double mixValue;

    public TmMixValue() {}

    public TmMixValue(TmMixValue value) {
        this.eleName = value.eleName;
        this.mixId = value.mixId;
        this.mixValue = value.mixValue;
    }

    public TmMixValue(
        String eleName,
        String mixId,
        Double mixValue
    ) {
        this.eleName = eleName;
        this.mixId = mixId;
        this.mixValue = mixValue;
    }

    public String getEleName() {
        return this.eleName;
    }

    public void setEleName(String eleName) {
        this.eleName = eleName;
    }

    public String getMixId() {
        return this.mixId;
    }

    public void setMixId(String mixId) {
        this.mixId = mixId;
    }

    public Double getMixValue() {
        return this.mixValue;
    }

    public void setMixValue(Double mixValue) {
        this.mixValue = mixValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmMixValue (");

        sb.append(eleName);
        sb.append(", ").append(mixId);
        sb.append(", ").append(mixValue);

        sb.append(")");
        return sb.toString();
    }
}
