/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmRole implements Serializable {

    private static final long serialVersionUID = -617104077;

    private Integer roleId;
    private String  roleName;
    private String  memo;

    public TmRole() {}

    public TmRole(TmRole value) {
        this.roleId = value.roleId;
        this.roleName = value.roleName;
        this.memo = value.memo;
    }

    public TmRole(
        Integer roleId,
        String  roleName,
        String  memo
    ) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.memo = memo;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmRole (");

        sb.append(roleId);
        sb.append(", ").append(roleName);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }
}
