/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmStdType implements Serializable {

    private static final long serialVersionUID = -1942359911;

    private String stdId;
    private String stdName;
    private String stdMemo;

    public TmStdType() {}

    public TmStdType(TmStdType value) {
        this.stdId = value.stdId;
        this.stdName = value.stdName;
        this.stdMemo = value.stdMemo;
    }

    public TmStdType(
        String stdId,
        String stdName,
        String stdMemo
    ) {
        this.stdId = stdId;
        this.stdName = stdName;
        this.stdMemo = stdMemo;
    }

    public String getStdId() {
        return this.stdId;
    }

    public void setStdId(String stdId) {
        this.stdId = stdId;
    }

    public String getStdName() {
        return this.stdName;
    }

    public void setStdName(String stdName) {
        this.stdName = stdName;
    }

    public String getStdMemo() {
        return this.stdMemo;
    }

    public void setStdMemo(String stdMemo) {
        this.stdMemo = stdMemo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmStdType (");

        sb.append(stdId);
        sb.append(", ").append(stdName);
        sb.append(", ").append(stdMemo);

        sb.append(")");
        return sb.toString();
    }
}
