/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmStdValue implements Serializable {

    private static final long serialVersionUID = -1444559432;

    private String eleName;
    private String stdId;
    private Double stdValue;

    public TmStdValue() {}

    public TmStdValue(TmStdValue value) {
        this.eleName = value.eleName;
        this.stdId = value.stdId;
        this.stdValue = value.stdValue;
    }

    public TmStdValue(
        String eleName,
        String stdId,
        Double stdValue
    ) {
        this.eleName = eleName;
        this.stdId = stdId;
        this.stdValue = stdValue;
    }

    public String getEleName() {
        return this.eleName;
    }

    public void setEleName(String eleName) {
        this.eleName = eleName;
    }

    public String getStdId() {
        return this.stdId;
    }

    public void setStdId(String stdId) {
        this.stdId = stdId;
    }

    public Double getStdValue() {
        return this.stdValue;
    }

    public void setStdValue(Double stdValue) {
        this.stdValue = stdValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmStdValue (");

        sb.append(eleName);
        sb.append(", ").append(stdId);
        sb.append(", ").append(stdValue);

        sb.append(")");
        return sb.toString();
    }
}
