/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmStdValue implements Serializable {

    private static final long serialVersionUID = 1820041880;

    private String  stdId;
    private Integer eleIndex;
    private Double  stdValue;

    public TmStdValue() {}

    public TmStdValue(TmStdValue value) {
        this.stdId = value.stdId;
        this.eleIndex = value.eleIndex;
        this.stdValue = value.stdValue;
    }

    public TmStdValue(
        String  stdId,
        Integer eleIndex,
        Double  stdValue
    ) {
        this.stdId = stdId;
        this.eleIndex = eleIndex;
        this.stdValue = stdValue;
    }

    public String getStdId() {
        return this.stdId;
    }

    public void setStdId(String stdId) {
        this.stdId = stdId;
    }

    public Integer getEleIndex() {
        return this.eleIndex;
    }

    public void setEleIndex(Integer eleIndex) {
        this.eleIndex = eleIndex;
    }

    public Double getStdValue() {
        return this.stdValue;
    }

    public void setStdValue(Double stdValue) {
        this.stdValue = stdValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TmStdValue (");

        sb.append(stdId);
        sb.append(", ").append(eleIndex);
        sb.append(", ").append(stdValue);

        sb.append(")");
        return sb.toString();
    }
}
