/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmBasicDataValue;
import com.jlu.magmalab.dao.tables.records.TmBasicDataValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmBasicDataValueDao extends DAOImpl<TmBasicDataValueRecord, com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue, Record2<String, Integer>> {

    /**
     * Create a new TmBasicDataValueDao without any configuration
     */
    public TmBasicDataValueDao() {
        super(TmBasicDataValue.TM_BASIC_DATA_VALUE, com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue.class);
    }

    /**
     * Create a new TmBasicDataValueDao with an attached configuration
     */
    public TmBasicDataValueDao(Configuration configuration) {
        super(TmBasicDataValue.TM_BASIC_DATA_VALUE, com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Integer> getId(com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue object) {
        return compositeKeyRecord(object.getDataId(), object.getEleIndex());
    }

    /**
     * Fetch records that have <code>DATA_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue> fetchByDataId(String... values) {
        return fetch(TmBasicDataValue.TM_BASIC_DATA_VALUE.DATA_ID, values);
    }

    /**
     * Fetch records that have <code>ELE_INDEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue> fetchByEleIndex(Integer... values) {
        return fetch(TmBasicDataValue.TM_BASIC_DATA_VALUE.ELE_INDEX, values);
    }

    /**
     * Fetch records that have <code>DATA_VALUE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmBasicDataValue> fetchByDataValue(Double... values) {
        return fetch(TmBasicDataValue.TM_BASIC_DATA_VALUE.DATA_VALUE, values);
    }
}
