/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmDistributeValue;
import com.jlu.magmalab.dao.tables.records.TmDistributeValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDistributeValueDao extends DAOImpl<TmDistributeValueRecord, com.jlu.magmalab.dao.tables.pojos.TmDistributeValue, Record3<Integer, Integer, Integer>> {

    /**
     * Create a new TmDistributeValueDao without any configuration
     */
    public TmDistributeValueDao() {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE, com.jlu.magmalab.dao.tables.pojos.TmDistributeValue.class);
    }

    /**
     * Create a new TmDistributeValueDao with an attached configuration
     */
    public TmDistributeValueDao(Configuration configuration) {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE, com.jlu.magmalab.dao.tables.pojos.TmDistributeValue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record3<Integer, Integer, Integer> getId(com.jlu.magmalab.dao.tables.pojos.TmDistributeValue object) {
        return compositeKeyRecord(object.getEleIndex(), object.getMineralIndex(), object.getMeltIndex());
    }

    /**
     * Fetch records that have <code>ELE_INDEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByEleIndex(Integer... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.ELE_INDEX, values);
    }

    /**
     * Fetch records that have <code>MINERAL_INDEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByMineralIndex(Integer... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.MINERAL_INDEX, values);
    }

    /**
     * Fetch records that have <code>MELT_INDEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByMeltIndex(Integer... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.MELT_INDEX, values);
    }

    /**
     * Fetch records that have <code>DISTRIBUTE_VALUE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByDistributeValue(Double... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE, values);
    }
}
