/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmDistributeValue;
import com.jlu.magmalab.dao.tables.records.TmDistributeValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDistributeValueDao extends DAOImpl<TmDistributeValueRecord, com.jlu.magmalab.dao.tables.pojos.TmDistributeValue, Record3<String, String, String>> {

    /**
     * Create a new TmDistributeValueDao without any configuration
     */
    public TmDistributeValueDao() {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE, com.jlu.magmalab.dao.tables.pojos.TmDistributeValue.class);
    }

    /**
     * Create a new TmDistributeValueDao with an attached configuration
     */
    public TmDistributeValueDao(Configuration configuration) {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE, com.jlu.magmalab.dao.tables.pojos.TmDistributeValue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record3<String, String, String> getId(com.jlu.magmalab.dao.tables.pojos.TmDistributeValue object) {
        return compositeKeyRecord(object.getEleName(), object.getMineralId(), object.getMeltType());
    }

    /**
     * Fetch records that have <code>ELE_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByEleName(String... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.ELE_NAME, values);
    }

    /**
     * Fetch records that have <code>MINERAL_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByMineralId(String... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.MINERAL_ID, values);
    }

    /**
     * Fetch records that have <code>MELT_TYPE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByMeltType(String... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.MELT_TYPE, values);
    }

    /**
     * Fetch records that have <code>DISTRIBUTE_VALUE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmDistributeValue> fetchByDistributeValue(Double... values) {
        return fetch(TmDistributeValue.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE, values);
    }
}
