/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmElement;
import com.jlu.magmalab.dao.tables.records.TmElementRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmElementDao extends DAOImpl<TmElementRecord, com.jlu.magmalab.dao.tables.pojos.TmElement, Integer> {

    /**
     * Create a new TmElementDao without any configuration
     */
    public TmElementDao() {
        super(TmElement.TM_ELEMENT, com.jlu.magmalab.dao.tables.pojos.TmElement.class);
    }

    /**
     * Create a new TmElementDao with an attached configuration
     */
    public TmElementDao(Configuration configuration) {
        super(TmElement.TM_ELEMENT, com.jlu.magmalab.dao.tables.pojos.TmElement.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.jlu.magmalab.dao.tables.pojos.TmElement object) {
        return object.getIndex();
    }

    /**
     * Fetch records that have <code>INDEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmElement> fetchByIndex(Integer... values) {
        return fetch(TmElement.TM_ELEMENT.INDEX, values);
    }

    /**
     * Fetch a unique record that has <code>INDEX = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmElement fetchOneByIndex(Integer value) {
        return fetchOne(TmElement.TM_ELEMENT.INDEX, value);
    }

    /**
     * Fetch records that have <code>ELEMENT_CODE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmElement> fetchByElementCode(String... values) {
        return fetch(TmElement.TM_ELEMENT.ELEMENT_CODE, values);
    }

    /**
     * Fetch records that have <code>ELEMENT_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmElement> fetchByElementName(String... values) {
        return fetch(TmElement.TM_ELEMENT.ELEMENT_NAME, values);
    }

    /**
     * Fetch records that have <code>ELEMENT_PRONOUNCE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmElement> fetchByElementPronounce(String... values) {
        return fetch(TmElement.TM_ELEMENT.ELEMENT_PRONOUNCE, values);
    }
}
