/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmExpr;
import com.jlu.magmalab.dao.tables.records.TmExprRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmExprDao extends DAOImpl<TmExprRecord, com.jlu.magmalab.dao.tables.pojos.TmExpr, String> {

    /**
     * Create a new TmExprDao without any configuration
     */
    public TmExprDao() {
        super(TmExpr.TM_EXPR, com.jlu.magmalab.dao.tables.pojos.TmExpr.class);
    }

    /**
     * Create a new TmExprDao with an attached configuration
     */
    public TmExprDao(Configuration configuration) {
        super(TmExpr.TM_EXPR, com.jlu.magmalab.dao.tables.pojos.TmExpr.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jlu.magmalab.dao.tables.pojos.TmExpr object) {
        return object.getExprId();
    }

    /**
     * Fetch records that have <code>EXPR_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmExpr> fetchByExprId(String... values) {
        return fetch(TmExpr.TM_EXPR.EXPR_ID, values);
    }

    /**
     * Fetch a unique record that has <code>EXPR_ID = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmExpr fetchOneByExprId(String value) {
        return fetchOne(TmExpr.TM_EXPR.EXPR_ID, value);
    }

    /**
     * Fetch records that have <code>EXPR_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmExpr> fetchByExprName(String... values) {
        return fetch(TmExpr.TM_EXPR.EXPR_NAME, values);
    }

    /**
     * Fetch records that have <code>EXPR_CLASS_PATH IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmExpr> fetchByExprClassPath(String... values) {
        return fetch(TmExpr.TM_EXPR.EXPR_CLASS_PATH, values);
    }

    /**
     * Fetch records that have <code>EXPR_TYPE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmExpr> fetchByExprType(Integer... values) {
        return fetch(TmExpr.TM_EXPR.EXPR_TYPE, values);
    }

    /**
     * Fetch records that have <code>MEMO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmExpr> fetchByMemo(String... values) {
        return fetch(TmExpr.TM_EXPR.MEMO, values);
    }
}
