/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmInitialType;
import com.jlu.magmalab.dao.tables.records.TmInitialTypeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmInitialTypeDao extends DAOImpl<TmInitialTypeRecord, com.jlu.magmalab.dao.tables.pojos.TmInitialType, String> {

    /**
     * Create a new TmInitialTypeDao without any configuration
     */
    public TmInitialTypeDao() {
        super(TmInitialType.TM_INITIAL_TYPE, com.jlu.magmalab.dao.tables.pojos.TmInitialType.class);
    }

    /**
     * Create a new TmInitialTypeDao with an attached configuration
     */
    public TmInitialTypeDao(Configuration configuration) {
        super(TmInitialType.TM_INITIAL_TYPE, com.jlu.magmalab.dao.tables.pojos.TmInitialType.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jlu.magmalab.dao.tables.pojos.TmInitialType object) {
        return object.getInitialId();
    }

    /**
     * Fetch records that have <code>INITIAL_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialType> fetchByInitialId(String... values) {
        return fetch(TmInitialType.TM_INITIAL_TYPE.INITIAL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>INITIAL_ID = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmInitialType fetchOneByInitialId(String value) {
        return fetchOne(TmInitialType.TM_INITIAL_TYPE.INITIAL_ID, value);
    }

    /**
     * Fetch records that have <code>INITIAL_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialType> fetchByInitialName(String... values) {
        return fetch(TmInitialType.TM_INITIAL_TYPE.INITIAL_NAME, values);
    }

    /**
     * Fetch records that have <code>INITIAL_TYP IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialType> fetchByInitialTyp(Integer... values) {
        return fetch(TmInitialType.TM_INITIAL_TYPE.INITIAL_TYP, values);
    }

    /**
     * Fetch records that have <code>MEMO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialType> fetchByMemo(String... values) {
        return fetch(TmInitialType.TM_INITIAL_TYPE.MEMO, values);
    }
}
