/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmInitialValue;
import com.jlu.magmalab.dao.tables.records.TmInitialValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmInitialValueDao extends DAOImpl<TmInitialValueRecord, com.jlu.magmalab.dao.tables.pojos.TmInitialValue, Record2<String, Integer>> {

    /**
     * Create a new TmInitialValueDao without any configuration
     */
    public TmInitialValueDao() {
        super(TmInitialValue.TM_INITIAL_VALUE, com.jlu.magmalab.dao.tables.pojos.TmInitialValue.class);
    }

    /**
     * Create a new TmInitialValueDao with an attached configuration
     */
    public TmInitialValueDao(Configuration configuration) {
        super(TmInitialValue.TM_INITIAL_VALUE, com.jlu.magmalab.dao.tables.pojos.TmInitialValue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Integer> getId(com.jlu.magmalab.dao.tables.pojos.TmInitialValue object) {
        return compositeKeyRecord(object.getInitialId(), object.getEleIndex());
    }

    /**
     * Fetch records that have <code>INITIAL_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialValue> fetchByInitialId(String... values) {
        return fetch(TmInitialValue.TM_INITIAL_VALUE.INITIAL_ID, values);
    }

    /**
     * Fetch records that have <code>ELE_INDEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialValue> fetchByEleIndex(Integer... values) {
        return fetch(TmInitialValue.TM_INITIAL_VALUE.ELE_INDEX, values);
    }

    /**
     * Fetch records that have <code>INITIAL_VALUE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmInitialValue> fetchByInitialValue(Double... values) {
        return fetch(TmInitialValue.TM_INITIAL_VALUE.INITIAL_VALUE, values);
    }
}
