/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmLabReport;
import com.jlu.magmalab.dao.tables.records.TmLabReportRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmLabReportDao extends DAOImpl<TmLabReportRecord, com.jlu.magmalab.dao.tables.pojos.TmLabReport, String> {

    /**
     * Create a new TmLabReportDao without any configuration
     */
    public TmLabReportDao() {
        super(TmLabReport.TM_LAB_REPORT, com.jlu.magmalab.dao.tables.pojos.TmLabReport.class);
    }

    /**
     * Create a new TmLabReportDao with an attached configuration
     */
    public TmLabReportDao(Configuration configuration) {
        super(TmLabReport.TM_LAB_REPORT, com.jlu.magmalab.dao.tables.pojos.TmLabReport.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jlu.magmalab.dao.tables.pojos.TmLabReport object) {
        return object.getReportId();
    }

    /**
     * Fetch records that have <code>REPORT_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmLabReport> fetchByReportId(String... values) {
        return fetch(TmLabReport.TM_LAB_REPORT.REPORT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>REPORT_ID = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmLabReport fetchOneByReportId(String value) {
        return fetchOne(TmLabReport.TM_LAB_REPORT.REPORT_ID, value);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmLabReport> fetchByUserId(String... values) {
        return fetch(TmLabReport.TM_LAB_REPORT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>UPD_TIME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmLabReport> fetchByUpdTime(Timestamp... values) {
        return fetch(TmLabReport.TM_LAB_REPORT.UPD_TIME, values);
    }

    /**
     * Fetch records that have <code>REPORT_SCORE IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmLabReport> fetchByReportScore(Integer... values) {
        return fetch(TmLabReport.TM_LAB_REPORT.REPORT_SCORE, values);
    }

    /**
     * Fetch records that have <code>REPORT_TEACHER_STATUS IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmLabReport> fetchByReportTeacherStatus(Integer... values) {
        return fetch(TmLabReport.TM_LAB_REPORT.REPORT_TEACHER_STATUS, values);
    }

    /**
     * Fetch records that have <code>REPORT_STUDENT_STATUS IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmLabReport> fetchByReportStudentStatus(Integer... values) {
        return fetch(TmLabReport.TM_LAB_REPORT.REPORT_STUDENT_STATUS, values);
    }
}
