/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmMixType;
import com.jlu.magmalab.dao.tables.records.TmMixTypeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMixTypeDao extends DAOImpl<TmMixTypeRecord, com.jlu.magmalab.dao.tables.pojos.TmMixType, Record2<String, String>> {

    /**
     * Create a new TmMixTypeDao without any configuration
     */
    public TmMixTypeDao() {
        super(TmMixType.TM_MIX_TYPE, com.jlu.magmalab.dao.tables.pojos.TmMixType.class);
    }

    /**
     * Create a new TmMixTypeDao with an attached configuration
     */
    public TmMixTypeDao(Configuration configuration) {
        super(TmMixType.TM_MIX_TYPE, com.jlu.magmalab.dao.tables.pojos.TmMixType.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.jlu.magmalab.dao.tables.pojos.TmMixType object) {
        return compositeKeyRecord(object.getMixId(), object.getMixName());
    }

    /**
     * Fetch records that have <code>MIX_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmMixType> fetchByMixId(String... values) {
        return fetch(TmMixType.TM_MIX_TYPE.MIX_ID, values);
    }

    /**
     * Fetch records that have <code>MIX_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmMixType> fetchByMixName(String... values) {
        return fetch(TmMixType.TM_MIX_TYPE.MIX_NAME, values);
    }

    /**
     * Fetch records that have <code>MIX_MEMO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmMixType> fetchByMixMemo(String... values) {
        return fetch(TmMixType.TM_MIX_TYPE.MIX_MEMO, values);
    }
}
