/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmRole;
import com.jlu.magmalab.dao.tables.records.TmRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmRoleDao extends DAOImpl<TmRoleRecord, com.jlu.magmalab.dao.tables.pojos.TmRole, Integer> {

    /**
     * Create a new TmRoleDao without any configuration
     */
    public TmRoleDao() {
        super(TmRole.TM_ROLE, com.jlu.magmalab.dao.tables.pojos.TmRole.class);
    }

    /**
     * Create a new TmRoleDao with an attached configuration
     */
    public TmRoleDao(Configuration configuration) {
        super(TmRole.TM_ROLE, com.jlu.magmalab.dao.tables.pojos.TmRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.jlu.magmalab.dao.tables.pojos.TmRole object) {
        return object.getRoleId();
    }

    /**
     * Fetch records that have <code>ROLE_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmRole> fetchByRoleId(Integer... values) {
        return fetch(TmRole.TM_ROLE.ROLE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>ROLE_ID = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmRole fetchOneByRoleId(Integer value) {
        return fetchOne(TmRole.TM_ROLE.ROLE_ID, value);
    }

    /**
     * Fetch records that have <code>ROLE_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmRole> fetchByRoleName(String... values) {
        return fetch(TmRole.TM_ROLE.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>MEMO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmRole> fetchByMemo(String... values) {
        return fetch(TmRole.TM_ROLE.MEMO, values);
    }
}
