/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmStdType;
import com.jlu.magmalab.dao.tables.records.TmStdTypeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmStdTypeDao extends DAOImpl<TmStdTypeRecord, com.jlu.magmalab.dao.tables.pojos.TmStdType, String> {

    /**
     * Create a new TmStdTypeDao without any configuration
     */
    public TmStdTypeDao() {
        super(TmStdType.TM_STD_TYPE, com.jlu.magmalab.dao.tables.pojos.TmStdType.class);
    }

    /**
     * Create a new TmStdTypeDao with an attached configuration
     */
    public TmStdTypeDao(Configuration configuration) {
        super(TmStdType.TM_STD_TYPE, com.jlu.magmalab.dao.tables.pojos.TmStdType.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jlu.magmalab.dao.tables.pojos.TmStdType object) {
        return object.getStdId();
    }

    /**
     * Fetch records that have <code>STD_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmStdType> fetchByStdId(String... values) {
        return fetch(TmStdType.TM_STD_TYPE.STD_ID, values);
    }

    /**
     * Fetch a unique record that has <code>STD_ID = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmStdType fetchOneByStdId(String value) {
        return fetchOne(TmStdType.TM_STD_TYPE.STD_ID, value);
    }

    /**
     * Fetch records that have <code>STD_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmStdType> fetchByStdName(String... values) {
        return fetch(TmStdType.TM_STD_TYPE.STD_NAME, values);
    }

    /**
     * Fetch records that have <code>STD_MEMO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmStdType> fetchByStdMemo(String... values) {
        return fetch(TmStdType.TM_STD_TYPE.STD_MEMO, values);
    }
}
