/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmUser;
import com.jlu.magmalab.dao.tables.records.TmUserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmUserDao extends DAOImpl<TmUserRecord, com.jlu.magmalab.dao.tables.pojos.TmUser, String> {

    /**
     * Create a new TmUserDao without any configuration
     */
    public TmUserDao() {
        super(TmUser.TM_USER, com.jlu.magmalab.dao.tables.pojos.TmUser.class);
    }

    /**
     * Create a new TmUserDao with an attached configuration
     */
    public TmUserDao(Configuration configuration) {
        super(TmUser.TM_USER, com.jlu.magmalab.dao.tables.pojos.TmUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jlu.magmalab.dao.tables.pojos.TmUser object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByUserId(String... values) {
        return fetch(TmUser.TM_USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>USER_ID = value</code>
     */
    public com.jlu.magmalab.dao.tables.pojos.TmUser fetchOneByUserId(String value) {
        return fetchOne(TmUser.TM_USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>LOGIN_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByLoginId(String... values) {
        return fetch(TmUser.TM_USER.LOGIN_ID, values);
    }

    /**
     * Fetch records that have <code>PASSWORD IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByPassword(String... values) {
        return fetch(TmUser.TM_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>USER_NAME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByUserName(String... values) {
        return fetch(TmUser.TM_USER.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>SEX IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchBySex(Integer... values) {
        return fetch(TmUser.TM_USER.SEX, values);
    }

    /**
     * Fetch records that have <code>PHONE_NO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByPhoneNo(String... values) {
        return fetch(TmUser.TM_USER.PHONE_NO, values);
    }

    /**
     * Fetch records that have <code>MEMO IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByMemo(String... values) {
        return fetch(TmUser.TM_USER.MEMO, values);
    }

    /**
     * Fetch records that have <code>UPD_TIME IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByUpdTime(Timestamp... values) {
        return fetch(TmUser.TM_USER.UPD_TIME, values);
    }

    /**
     * Fetch records that have <code>PWD_STATUS IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUser> fetchByPwdStatus(Integer... values) {
        return fetch(TmUser.TM_USER.PWD_STATUS, values);
    }
}
