/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.daos;


import com.jlu.magmalab.dao.tables.TmUserRole;
import com.jlu.magmalab.dao.tables.records.TmUserRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmUserRoleDao extends DAOImpl<TmUserRoleRecord, com.jlu.magmalab.dao.tables.pojos.TmUserRole, Record2<String, String>> {

    /**
     * Create a new TmUserRoleDao without any configuration
     */
    public TmUserRoleDao() {
        super(TmUserRole.TM_USER_ROLE, com.jlu.magmalab.dao.tables.pojos.TmUserRole.class);
    }

    /**
     * Create a new TmUserRoleDao with an attached configuration
     */
    public TmUserRoleDao(Configuration configuration) {
        super(TmUserRole.TM_USER_ROLE, com.jlu.magmalab.dao.tables.pojos.TmUserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.jlu.magmalab.dao.tables.pojos.TmUserRole object) {
        return compositeKeyRecord(object.getUserId(), object.getRoleId());
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUserRole> fetchByUserId(String... values) {
        return fetch(TmUserRole.TM_USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>ROLE_ID IN (values)</code>
     */
    public List<com.jlu.magmalab.dao.tables.pojos.TmUserRole> fetchByRoleId(String... values) {
        return fetch(TmUserRole.TM_USER_ROLE.ROLE_ID, values);
    }
}
