/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables;


import com.jlu.magmalab.dao.Indexes;
import com.jlu.magmalab.dao.Keys;
import com.jlu.magmalab.dao.Magmlab;
import com.jlu.magmalab.dao.tables.records.TmElementRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmElement extends TableImpl<TmElementRecord> {

    private static final long serialVersionUID = -626576065;

    /**
     * The reference instance of <code>magmLab.TM_ELEMENT</code>
     */
    public static final TmElement TM_ELEMENT = new TmElement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmElementRecord> getRecordType() {
        return TmElementRecord.class;
    }

    /**
     * The column <code>magmLab.TM_ELEMENT.INDEX</code>. 序号
     */
    public final TableField<TmElementRecord, Integer> INDEX = createField("INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "序号");

    /**
     * The column <code>magmLab.TM_ELEMENT.ELEMENT_CODE</code>. 元素编码
     */
    public final TableField<TmElementRecord, String> ELEMENT_CODE = createField("ELEMENT_CODE", org.jooq.impl.SQLDataType.CHAR(200), this, "元素编码");

    /**
     * The column <code>magmLab.TM_ELEMENT.ELEMENT_NAME</code>. 元素名称
     */
    public final TableField<TmElementRecord, String> ELEMENT_NAME = createField("ELEMENT_NAME", org.jooq.impl.SQLDataType.CHAR(200), this, "元素名称");

    /**
     * The column <code>magmLab.TM_ELEMENT.ELEMENT_PRONOUNCE</code>. 元素发音
     */
    public final TableField<TmElementRecord, String> ELEMENT_PRONOUNCE = createField("ELEMENT_PRONOUNCE", org.jooq.impl.SQLDataType.CHAR(200), this, "元素发音");

    /**
     * Create a <code>magmLab.TM_ELEMENT</code> table reference
     */
    public TmElement() {
        this(DSL.name("TM_ELEMENT"), null);
    }

    /**
     * Create an aliased <code>magmLab.TM_ELEMENT</code> table reference
     */
    public TmElement(String alias) {
        this(DSL.name(alias), TM_ELEMENT);
    }

    /**
     * Create an aliased <code>magmLab.TM_ELEMENT</code> table reference
     */
    public TmElement(Name alias) {
        this(alias, TM_ELEMENT);
    }

    private TmElement(Name alias, Table<TmElementRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmElement(Name alias, Table<TmElementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Magmlab.MAGMLAB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TM_ELEMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TmElementRecord> getPrimaryKey() {
        return Keys.KEY_TM_ELEMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TmElementRecord>> getKeys() {
        return Arrays.<UniqueKey<TmElementRecord>>asList(Keys.KEY_TM_ELEMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmElement as(String alias) {
        return new TmElement(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmElement as(Name alias) {
        return new TmElement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TmElement rename(String name) {
        return new TmElement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TmElement rename(Name name) {
        return new TmElement(name, null);
    }
}
