/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables;


import com.jlu.magmalab.dao.Indexes;
import com.jlu.magmalab.dao.Keys;
import com.jlu.magmalab.dao.Magmlab;
import com.jlu.magmalab.dao.tables.records.TmMeltTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMeltType extends TableImpl<TmMeltTypeRecord> {

    private static final long serialVersionUID = 1587113567;

    /**
     * The reference instance of <code>magmLab.TM_MELT_TYPE</code>
     */
    public static final TmMeltType TM_MELT_TYPE = new TmMeltType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmMeltTypeRecord> getRecordType() {
        return TmMeltTypeRecord.class;
    }

    /**
     * The column <code>magmLab.TM_MELT_TYPE.MELT_NAME</code>.
     */
    public final TableField<TmMeltTypeRecord, String> MELT_NAME = createField("MELT_NAME", org.jooq.impl.SQLDataType.CHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>magmLab.TM_MELT_TYPE.INDEX</code>.
     */
    public final TableField<TmMeltTypeRecord, Integer> INDEX = createField("INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>magmLab.TM_MELT_TYPE.MEMO</code>.
     */
    public final TableField<TmMeltTypeRecord, String> MEMO = createField("MEMO", org.jooq.impl.SQLDataType.CHAR(200), this, "");

    /**
     * Create a <code>magmLab.TM_MELT_TYPE</code> table reference
     */
    public TmMeltType() {
        this(DSL.name("TM_MELT_TYPE"), null);
    }

    /**
     * Create an aliased <code>magmLab.TM_MELT_TYPE</code> table reference
     */
    public TmMeltType(String alias) {
        this(DSL.name(alias), TM_MELT_TYPE);
    }

    /**
     * Create an aliased <code>magmLab.TM_MELT_TYPE</code> table reference
     */
    public TmMeltType(Name alias) {
        this(alias, TM_MELT_TYPE);
    }

    private TmMeltType(Name alias, Table<TmMeltTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmMeltType(Name alias, Table<TmMeltTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Magmlab.MAGMLAB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TM_MELT_TYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TmMeltTypeRecord> getPrimaryKey() {
        return Keys.KEY_TM_MELT_TYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TmMeltTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<TmMeltTypeRecord>>asList(Keys.KEY_TM_MELT_TYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMeltType as(String alias) {
        return new TmMeltType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMeltType as(Name alias) {
        return new TmMeltType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TmMeltType rename(String name) {
        return new TmMeltType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TmMeltType rename(Name name) {
        return new TmMeltType(name, null);
    }
}
