/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables;


import com.jlu.magmalab.dao.Indexes;
import com.jlu.magmalab.dao.Keys;
import com.jlu.magmalab.dao.Magmlab;
import com.jlu.magmalab.dao.tables.records.TmMixValueRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMixValue extends TableImpl<TmMixValueRecord> {

    private static final long serialVersionUID = 1332821050;

    /**
     * The reference instance of <code>magmLab.TM_MIX_VALUE</code>
     */
    public static final TmMixValue TM_MIX_VALUE = new TmMixValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmMixValueRecord> getRecordType() {
        return TmMixValueRecord.class;
    }

    /**
     * The column <code>magmLab.TM_MIX_VALUE.MIX_ID</code>. UUID
     */
    public final TableField<TmMixValueRecord, String> MIX_ID = createField("MIX_ID", org.jooq.impl.SQLDataType.CHAR(48).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "UUID");

    /**
     * The column <code>magmLab.TM_MIX_VALUE.ELE_INDEX</code>.
     */
    public final TableField<TmMixValueRecord, Integer> ELE_INDEX = createField("ELE_INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>magmLab.TM_MIX_VALUE.MIX_VALUE</code>.
     */
    public final TableField<TmMixValueRecord, Double> MIX_VALUE = createField("MIX_VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>magmLab.TM_MIX_VALUE</code> table reference
     */
    public TmMixValue() {
        this(DSL.name("TM_MIX_VALUE"), null);
    }

    /**
     * Create an aliased <code>magmLab.TM_MIX_VALUE</code> table reference
     */
    public TmMixValue(String alias) {
        this(DSL.name(alias), TM_MIX_VALUE);
    }

    /**
     * Create an aliased <code>magmLab.TM_MIX_VALUE</code> table reference
     */
    public TmMixValue(Name alias) {
        this(alias, TM_MIX_VALUE);
    }

    private TmMixValue(Name alias, Table<TmMixValueRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmMixValue(Name alias, Table<TmMixValueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Magmlab.MAGMLAB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TM_MIX_VALUE_FK_RELATIONSHIP_1, Indexes.TM_MIX_VALUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TmMixValueRecord> getPrimaryKey() {
        return Keys.KEY_TM_MIX_VALUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TmMixValueRecord>> getKeys() {
        return Arrays.<UniqueKey<TmMixValueRecord>>asList(Keys.KEY_TM_MIX_VALUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMixValue as(String alias) {
        return new TmMixValue(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMixValue as(Name alias) {
        return new TmMixValue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TmMixValue rename(String name) {
        return new TmMixValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TmMixValue rename(Name name) {
        return new TmMixValue(name, null);
    }
}
