/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables;


import com.jlu.magmalab.dao.Indexes;
import com.jlu.magmalab.dao.Keys;
import com.jlu.magmalab.dao.Magmlab;
import com.jlu.magmalab.dao.tables.records.TmMineralRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMineral extends TableImpl<TmMineralRecord> {

    private static final long serialVersionUID = 36029770;

    /**
     * The reference instance of <code>magmLab.TM_MINERAL</code>
     */
    public static final TmMineral TM_MINERAL = new TmMineral();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmMineralRecord> getRecordType() {
        return TmMineralRecord.class;
    }

    /**
     * The column <code>magmLab.TM_MINERAL.INDEX</code>.
     */
    public final TableField<TmMineralRecord, Integer> INDEX = createField("INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>magmLab.TM_MINERAL.MINERAL_NAME</code>.
     */
    public final TableField<TmMineralRecord, String> MINERAL_NAME = createField("MINERAL_NAME", org.jooq.impl.SQLDataType.CHAR(100), this, "");

    /**
     * The column <code>magmLab.TM_MINERAL.MEMO</code>.
     */
    public final TableField<TmMineralRecord, String> MEMO = createField("MEMO", org.jooq.impl.SQLDataType.CHAR(200), this, "");

    /**
     * Create a <code>magmLab.TM_MINERAL</code> table reference
     */
    public TmMineral() {
        this(DSL.name("TM_MINERAL"), null);
    }

    /**
     * Create an aliased <code>magmLab.TM_MINERAL</code> table reference
     */
    public TmMineral(String alias) {
        this(DSL.name(alias), TM_MINERAL);
    }

    /**
     * Create an aliased <code>magmLab.TM_MINERAL</code> table reference
     */
    public TmMineral(Name alias) {
        this(alias, TM_MINERAL);
    }

    private TmMineral(Name alias, Table<TmMineralRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmMineral(Name alias, Table<TmMineralRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Magmlab.MAGMLAB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TM_MINERAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TmMineralRecord> getPrimaryKey() {
        return Keys.KEY_TM_MINERAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TmMineralRecord>> getKeys() {
        return Arrays.<UniqueKey<TmMineralRecord>>asList(Keys.KEY_TM_MINERAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMineral as(String alias) {
        return new TmMineral(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMineral as(Name alias) {
        return new TmMineral(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TmMineral rename(String name) {
        return new TmMineral(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TmMineral rename(Name name) {
        return new TmMineral(name, null);
    }
}
