/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao;


import com.jlu.magmalab.dao.tables.TmDistributeValue;
import com.jlu.magmalab.dao.tables.TmElement;
import com.jlu.magmalab.dao.tables.TmMeltType;
import com.jlu.magmalab.dao.tables.TmMineral;
import com.jlu.magmalab.dao.tables.TmMixType;
import com.jlu.magmalab.dao.tables.TmMixValue;
import com.jlu.magmalab.dao.tables.TmRole;
import com.jlu.magmalab.dao.tables.TmStdType;
import com.jlu.magmalab.dao.tables.TmStdValue;
import com.jlu.magmalab.dao.tables.TmUser;
import com.jlu.magmalab.dao.tables.TmUserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Magmlab extends SchemaImpl {

    private static final long serialVersionUID = -1823932352;

    /**
     * The reference instance of <code>magmLab</code>
     */
    public static final Magmlab MAGMLAB = new Magmlab();

    /**
     * The table <code>magmLab.TM_DISTRIBUTE_VALUE</code>.
     */
    public final TmDistributeValue TM_DISTRIBUTE_VALUE = com.jlu.magmalab.dao.tables.TmDistributeValue.TM_DISTRIBUTE_VALUE;

    /**
     * The table <code>magmLab.TM_ELEMENT</code>.
     */
    public final TmElement TM_ELEMENT = com.jlu.magmalab.dao.tables.TmElement.TM_ELEMENT;

    /**
     * The table <code>magmLab.TM_MELT_TYPE</code>.
     */
    public final TmMeltType TM_MELT_TYPE = com.jlu.magmalab.dao.tables.TmMeltType.TM_MELT_TYPE;

    /**
     * The table <code>magmLab.TM_MINERAL</code>.
     */
    public final TmMineral TM_MINERAL = com.jlu.magmalab.dao.tables.TmMineral.TM_MINERAL;

    /**
     * The table <code>magmLab.TM_MIX_TYPE</code>.
     */
    public final TmMixType TM_MIX_TYPE = com.jlu.magmalab.dao.tables.TmMixType.TM_MIX_TYPE;

    /**
     * The table <code>magmLab.TM_MIX_VALUE</code>.
     */
    public final TmMixValue TM_MIX_VALUE = com.jlu.magmalab.dao.tables.TmMixValue.TM_MIX_VALUE;

    /**
     * The table <code>magmLab.TM_ROLE</code>.
     */
    public final TmRole TM_ROLE = com.jlu.magmalab.dao.tables.TmRole.TM_ROLE;

    /**
     * The table <code>magmLab.TM_STD_TYPE</code>.
     */
    public final TmStdType TM_STD_TYPE = com.jlu.magmalab.dao.tables.TmStdType.TM_STD_TYPE;

    /**
     * The table <code>magmLab.TM_STD_VALUE</code>.
     */
    public final TmStdValue TM_STD_VALUE = com.jlu.magmalab.dao.tables.TmStdValue.TM_STD_VALUE;

    /**
     * 用户表
     */
    public final TmUser TM_USER = com.jlu.magmalab.dao.tables.TmUser.TM_USER;

    /**
     * The table <code>magmLab.TM_USER_ROLE</code>.
     */
    public final TmUserRole TM_USER_ROLE = com.jlu.magmalab.dao.tables.TmUserRole.TM_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Magmlab() {
        super("magmLab", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TmDistributeValue.TM_DISTRIBUTE_VALUE,
            TmElement.TM_ELEMENT,
            TmMeltType.TM_MELT_TYPE,
            TmMineral.TM_MINERAL,
            TmMixType.TM_MIX_TYPE,
            TmMixValue.TM_MIX_VALUE,
            TmRole.TM_ROLE,
            TmStdType.TM_STD_TYPE,
            TmStdValue.TM_STD_VALUE,
            TmUser.TM_USER,
            TmUserRole.TM_USER_ROLE);
    }
}
