/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao;


import com.jlu.magmalab.dao.tables.TmBasicDataType;
import com.jlu.magmalab.dao.tables.TmBasicDataValue;
import com.jlu.magmalab.dao.tables.TmDistributeValue;
import com.jlu.magmalab.dao.tables.TmElement;
import com.jlu.magmalab.dao.tables.TmExpr;
import com.jlu.magmalab.dao.tables.TmMeltType;
import com.jlu.magmalab.dao.tables.TmMineral;
import com.jlu.magmalab.dao.tables.TmRole;
import com.jlu.magmalab.dao.tables.TmUser;
import com.jlu.magmalab.dao.tables.TmUserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Magmlab extends SchemaImpl {

    private static final long serialVersionUID = 43311568;

    /**
     * The reference instance of <code>magmLab</code>
     */
    public static final Magmlab MAGMLAB = new Magmlab();

    /**
     * The table <code>magmLab.TM_BASIC_DATA_TYPE</code>.
     */
    public final TmBasicDataType TM_BASIC_DATA_TYPE = com.jlu.magmalab.dao.tables.TmBasicDataType.TM_BASIC_DATA_TYPE;

    /**
     * The table <code>magmLab.TM_BASIC_DATA_VALUE</code>.
     */
    public final TmBasicDataValue TM_BASIC_DATA_VALUE = com.jlu.magmalab.dao.tables.TmBasicDataValue.TM_BASIC_DATA_VALUE;

    /**
     * The table <code>magmLab.TM_DISTRIBUTE_VALUE</code>.
     */
    public final TmDistributeValue TM_DISTRIBUTE_VALUE = com.jlu.magmalab.dao.tables.TmDistributeValue.TM_DISTRIBUTE_VALUE;

    /**
     * The table <code>magmLab.TM_ELEMENT</code>.
     */
    public final TmElement TM_ELEMENT = com.jlu.magmalab.dao.tables.TmElement.TM_ELEMENT;

    /**
     * The table <code>magmLab.TM_EXPR</code>.
     */
    public final TmExpr TM_EXPR = com.jlu.magmalab.dao.tables.TmExpr.TM_EXPR;

    /**
     * The table <code>magmLab.TM_MELT_TYPE</code>.
     */
    public final TmMeltType TM_MELT_TYPE = com.jlu.magmalab.dao.tables.TmMeltType.TM_MELT_TYPE;

    /**
     * The table <code>magmLab.TM_MINERAL</code>.
     */
    public final TmMineral TM_MINERAL = com.jlu.magmalab.dao.tables.TmMineral.TM_MINERAL;

    /**
     * The table <code>magmLab.TM_ROLE</code>.
     */
    public final TmRole TM_ROLE = com.jlu.magmalab.dao.tables.TmRole.TM_ROLE;

    /**
     * 用户表
     */
    public final TmUser TM_USER = com.jlu.magmalab.dao.tables.TmUser.TM_USER;

    /**
     * The table <code>magmLab.TM_USER_ROLE</code>.
     */
    public final TmUserRole TM_USER_ROLE = com.jlu.magmalab.dao.tables.TmUserRole.TM_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Magmlab() {
        super("magmLab", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TmBasicDataType.TM_BASIC_DATA_TYPE,
            TmBasicDataValue.TM_BASIC_DATA_VALUE,
            TmDistributeValue.TM_DISTRIBUTE_VALUE,
            TmElement.TM_ELEMENT,
            TmExpr.TM_EXPR,
            TmMeltType.TM_MELT_TYPE,
            TmMineral.TM_MINERAL,
            TmRole.TM_ROLE,
            TmUser.TM_USER,
            TmUserRole.TM_USER_ROLE);
    }
}
