/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmBasicDataValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmBasicDataValueRecord extends UpdatableRecordImpl<TmBasicDataValueRecord> implements Record3<String, Integer, Double> {

    private static final long serialVersionUID = -1926564113;

    /**
     * Setter for <code>magmLab.TM_BASIC_DATA_VALUE.DATA_ID</code>.
     */
    public void setDataId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_BASIC_DATA_VALUE.DATA_ID</code>.
     */
    public String getDataId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_BASIC_DATA_VALUE.ELE_INDEX</code>.
     */
    public void setEleIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_BASIC_DATA_VALUE.ELE_INDEX</code>.
     */
    public Integer getEleIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_BASIC_DATA_VALUE.DATA_VALUE</code>.
     */
    public void setDataValue(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_BASIC_DATA_VALUE.DATA_VALUE</code>.
     */
    public Double getDataValue() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmBasicDataValue.TM_BASIC_DATA_VALUE.DATA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TmBasicDataValue.TM_BASIC_DATA_VALUE.ELE_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return TmBasicDataValue.TM_BASIC_DATA_VALUE.DATA_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getEleIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getDataValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEleIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getDataValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmBasicDataValueRecord value1(String value) {
        setDataId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmBasicDataValueRecord value2(Integer value) {
        setEleIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmBasicDataValueRecord value3(Double value) {
        setDataValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmBasicDataValueRecord values(String value1, Integer value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmBasicDataValueRecord
     */
    public TmBasicDataValueRecord() {
        super(TmBasicDataValue.TM_BASIC_DATA_VALUE);
    }

    /**
     * Create a detached, initialised TmBasicDataValueRecord
     */
    public TmBasicDataValueRecord(String dataId, Integer eleIndex, Double dataValue) {
        super(TmBasicDataValue.TM_BASIC_DATA_VALUE);

        set(0, dataId);
        set(1, eleIndex);
        set(2, dataValue);
    }
}
