/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmDistributeValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDistributeValueRecord extends UpdatableRecordImpl<TmDistributeValueRecord> implements Record4<Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1543260376;

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.ELE_INDEX</code>.
     */
    public void setEleIndex(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.ELE_INDEX</code>.
     */
    public Integer getEleIndex() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.MINERAL_INDEX</code>.
     */
    public void setMineralIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.MINERAL_INDEX</code>.
     */
    public Integer getMineralIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.MELT_INDEX</code>.
     */
    public void setMeltIndex(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.MELT_INDEX</code>.
     */
    public Integer getMeltIndex() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE</code>.
     */
    public void setDistributeValue(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE</code>.
     */
    public Double getDistributeValue() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.ELE_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.MINERAL_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.MELT_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEleIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMineralIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMeltIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getDistributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEleIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMineralIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMeltIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getDistributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value1(Integer value) {
        setEleIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value2(Integer value) {
        setMineralIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value3(Integer value) {
        setMeltIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value4(Double value) {
        setDistributeValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord values(Integer value1, Integer value2, Integer value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmDistributeValueRecord
     */
    public TmDistributeValueRecord() {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE);
    }

    /**
     * Create a detached, initialised TmDistributeValueRecord
     */
    public TmDistributeValueRecord(Integer eleIndex, Integer mineralIndex, Integer meltIndex, Double distributeValue) {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE);

        set(0, eleIndex);
        set(1, mineralIndex);
        set(2, meltIndex);
        set(3, distributeValue);
    }
}
