/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmDistributeValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDistributeValueRecord extends UpdatableRecordImpl<TmDistributeValueRecord> implements Record4<String, String, String, Double> {

    private static final long serialVersionUID = -643943920;

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.ELE_NAME</code>.
     */
    public void setEleName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.ELE_NAME</code>.
     */
    public String getEleName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.MINERAL_ID</code>.
     */
    public void setMineralId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.MINERAL_ID</code>.
     */
    public String getMineralId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.MELT_TYPE</code>.
     */
    public void setMeltType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.MELT_TYPE</code>.
     */
    public String getMeltType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magmLab.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE</code>.
     */
    public void setDistributeValue(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>magmLab.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE</code>.
     */
    public Double getDistributeValue() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.ELE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.MINERAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.MELT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return TmDistributeValue.TM_DISTRIBUTE_VALUE.DISTRIBUTE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMineralId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMeltType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getDistributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMineralId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMeltType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getDistributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value1(String value) {
        setEleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value2(String value) {
        setMineralId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value3(String value) {
        setMeltType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord value4(Double value) {
        setDistributeValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDistributeValueRecord values(String value1, String value2, String value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmDistributeValueRecord
     */
    public TmDistributeValueRecord() {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE);
    }

    /**
     * Create a detached, initialised TmDistributeValueRecord
     */
    public TmDistributeValueRecord(String eleName, String mineralId, String meltType, Double distributeValue) {
        super(TmDistributeValue.TM_DISTRIBUTE_VALUE);

        set(0, eleName);
        set(1, mineralId);
        set(2, meltType);
        set(3, distributeValue);
    }
}
