/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmElement;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmElementRecord extends UpdatableRecordImpl<TmElementRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 101197132;

    /**
     * Setter for <code>magmLab.TM_ELEMENT.INDEX</code>.
     */
    public void setIndex(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_ELEMENT.INDEX</code>.
     */
    public Integer getIndex() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_ELEMENT.ELEMENT_NAME</code>.
     */
    public void setElementName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_ELEMENT.ELEMENT_NAME</code>.
     */
    public String getElementName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_ELEMENT.MEMO</code>.
     */
    public void setMemo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_ELEMENT.MEMO</code>.
     */
    public String getMemo() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TmElement.TM_ELEMENT.INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmElement.TM_ELEMENT.ELEMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmElement.TM_ELEMENT.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmElementRecord value1(Integer value) {
        setIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmElementRecord value2(String value) {
        setElementName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmElementRecord value3(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmElementRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmElementRecord
     */
    public TmElementRecord() {
        super(TmElement.TM_ELEMENT);
    }

    /**
     * Create a detached, initialised TmElementRecord
     */
    public TmElementRecord(Integer index, String elementName, String memo) {
        super(TmElement.TM_ELEMENT);

        set(0, index);
        set(1, elementName);
        set(2, memo);
    }
}
