/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmExpr;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmExprRecord extends UpdatableRecordImpl<TmExprRecord> implements Record5<String, String, String, Integer, String> {

    private static final long serialVersionUID = 509861816;

    /**
     * Setter for <code>magmLab.TM_EXPR.EXPR_ID</code>. UUID
     */
    public void setExprId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_EXPR.EXPR_ID</code>. UUID
     */
    public String getExprId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_EXPR.EXPR_NAME</code>. 公式名称
     */
    public void setExprName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_EXPR.EXPR_NAME</code>. 公式名称
     */
    public String getExprName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_EXPR.EXPR_CLASS_PATH</code>. 类路径
     */
    public void setExprClassPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_EXPR.EXPR_CLASS_PATH</code>. 类路径
     */
    public String getExprClassPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magmLab.TM_EXPR.EXPR_TYPE</code>. 0:结晶 1：混染
     */
    public void setExprType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>magmLab.TM_EXPR.EXPR_TYPE</code>. 0:结晶 1：混染
     */
    public Integer getExprType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>magmLab.TM_EXPR.MEMO</code>. 备注
     */
    public void setMemo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>magmLab.TM_EXPR.MEMO</code>. 备注
     */
    public String getMemo() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmExpr.TM_EXPR.EXPR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmExpr.TM_EXPR.EXPR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmExpr.TM_EXPR.EXPR_CLASS_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TmExpr.TM_EXPR.EXPR_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TmExpr.TM_EXPR.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getExprId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExprName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExprClassPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getExprType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getExprId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExprName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExprClassPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getExprType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmExprRecord value1(String value) {
        setExprId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmExprRecord value2(String value) {
        setExprName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmExprRecord value3(String value) {
        setExprClassPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmExprRecord value4(Integer value) {
        setExprType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmExprRecord value5(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmExprRecord values(String value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmExprRecord
     */
    public TmExprRecord() {
        super(TmExpr.TM_EXPR);
    }

    /**
     * Create a detached, initialised TmExprRecord
     */
    public TmExprRecord(String exprId, String exprName, String exprClassPath, Integer exprType, String memo) {
        super(TmExpr.TM_EXPR);

        set(0, exprId);
        set(1, exprName);
        set(2, exprClassPath);
        set(3, exprType);
        set(4, memo);
    }
}
