/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmInitialValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmInitialValueRecord extends UpdatableRecordImpl<TmInitialValueRecord> implements Record3<String, Integer, Double> {

    private static final long serialVersionUID = 730123114;

    /**
     * Setter for <code>magmLab.TM_INITIAL_VALUE.INITIAL_ID</code>. 初始熔体ID
     */
    public void setInitialId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_VALUE.INITIAL_ID</code>. 初始熔体ID
     */
    public String getInitialId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_INITIAL_VALUE.ELE_INDEX</code>. 元素序号
     */
    public void setEleIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_VALUE.ELE_INDEX</code>. 元素序号
     */
    public Integer getEleIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_INITIAL_VALUE.INITIAL_VALUE</code>. 初始熔体值
     */
    public void setInitialValue(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_VALUE.INITIAL_VALUE</code>. 初始熔体值
     */
    public Double getInitialValue() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmInitialValue.TM_INITIAL_VALUE.INITIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TmInitialValue.TM_INITIAL_VALUE.ELE_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return TmInitialValue.TM_INITIAL_VALUE.INITIAL_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getInitialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getEleIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getInitialValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getInitialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEleIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getInitialValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialValueRecord value1(String value) {
        setInitialId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialValueRecord value2(Integer value) {
        setEleIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialValueRecord value3(Double value) {
        setInitialValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialValueRecord values(String value1, Integer value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmInitialValueRecord
     */
    public TmInitialValueRecord() {
        super(TmInitialValue.TM_INITIAL_VALUE);
    }

    /**
     * Create a detached, initialised TmInitialValueRecord
     */
    public TmInitialValueRecord(String initialId, Integer eleIndex, Double initialValue) {
        super(TmInitialValue.TM_INITIAL_VALUE);

        set(0, initialId);
        set(1, eleIndex);
        set(2, initialValue);
    }
}
