/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmInitialType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmInitialTypeRecord extends UpdatableRecordImpl<TmInitialTypeRecord> implements Record4<String, String, Integer, String> {

    private static final long serialVersionUID = 2073926248;

    /**
     * Setter for <code>magmLab.TM_INITIAL_TYPE.INITIAL_ID</code>. 初始熔体ID
     */
    public void setInitialId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_TYPE.INITIAL_ID</code>. 初始熔体ID
     */
    public String getInitialId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_INITIAL_TYPE.INITIAL_NAME</code>. 初始熔体名称
     */
    public void setInitialName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_TYPE.INITIAL_NAME</code>. 初始熔体名称
     */
    public String getInitialName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_INITIAL_TYPE.INITIAL_TYP</code>. 0:初始岩浆 1:初始熔体
     */
    public void setInitialTyp(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_TYPE.INITIAL_TYP</code>. 0:初始岩浆 1:初始熔体
     */
    public Integer getInitialTyp() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>magmLab.TM_INITIAL_TYPE.MEMO</code>. 备注
     */
    public void setMemo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>magmLab.TM_INITIAL_TYPE.MEMO</code>. 备注
     */
    public String getMemo() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmInitialType.TM_INITIAL_TYPE.INITIAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmInitialType.TM_INITIAL_TYPE.INITIAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TmInitialType.TM_INITIAL_TYPE.INITIAL_TYP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TmInitialType.TM_INITIAL_TYPE.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getInitialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getInitialName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getInitialTyp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getInitialId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInitialName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getInitialTyp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialTypeRecord value1(String value) {
        setInitialId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialTypeRecord value2(String value) {
        setInitialName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialTypeRecord value3(Integer value) {
        setInitialTyp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialTypeRecord value4(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmInitialTypeRecord values(String value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmInitialTypeRecord
     */
    public TmInitialTypeRecord() {
        super(TmInitialType.TM_INITIAL_TYPE);
    }

    /**
     * Create a detached, initialised TmInitialTypeRecord
     */
    public TmInitialTypeRecord(String initialId, String initialName, Integer initialTyp, String memo) {
        super(TmInitialType.TM_INITIAL_TYPE);

        set(0, initialId);
        set(1, initialName);
        set(2, initialTyp);
        set(3, memo);
    }
}
