/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmLabReport;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmLabReportRecord extends UpdatableRecordImpl<TmLabReportRecord> implements Record7<String, String, Timestamp, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1332973177;

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.REPORT_ID</code>. 实验报告ID
     */
    public void setReportId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.REPORT_ID</code>. 实验报告ID
     */
    public String getReportId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.USER_ID</code>. 用户ID
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.USER_ID</code>. 用户ID
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.UPD_TIME</code>. 更新时间
     */
    public void setUpdTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.UPD_TIME</code>. 更新时间
     */
    public Timestamp getUpdTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.REPORT_SCORE</code>. 报告得分
     */
    public void setReportScore(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.REPORT_SCORE</code>. 报告得分
     */
    public Integer getReportScore() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.REPORT_TEACHER_STATUS</code>. 0:未读  1:已读 
     */
    public void setReportTeacherStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.REPORT_TEACHER_STATUS</code>. 0:未读  1:已读 
     */
    public Integer getReportTeacherStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.REPORT_STUDENT_STATUS</code>. 0:未读  1:已读
     */
    public void setReportStudentStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.REPORT_STUDENT_STATUS</code>. 0:未读  1:已读
     */
    public Integer getReportStudentStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>magmLab.TM_LAB_REPORT.REPORT_STATUS</code>. 0:未批阅 1:已批阅
     */
    public void setReportStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>magmLab.TM_LAB_REPORT.REPORT_STATUS</code>. 0:未批阅 1:已批阅
     */
    public Integer getReportStatus() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Timestamp, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Timestamp, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmLabReport.TM_LAB_REPORT.REPORT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmLabReport.TM_LAB_REPORT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TmLabReport.TM_LAB_REPORT.UPD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TmLabReport.TM_LAB_REPORT.REPORT_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TmLabReport.TM_LAB_REPORT.REPORT_TEACHER_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TmLabReport.TM_LAB_REPORT.REPORT_STUDENT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TmLabReport.TM_LAB_REPORT.REPORT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getReportScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getReportTeacherStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getReportStudentStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getReportStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getReportScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getReportTeacherStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getReportStudentStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getReportStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value1(String value) {
        setReportId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value3(Timestamp value) {
        setUpdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value4(Integer value) {
        setReportScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value5(Integer value) {
        setReportTeacherStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value6(Integer value) {
        setReportStudentStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord value7(Integer value) {
        setReportStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmLabReportRecord values(String value1, String value2, Timestamp value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmLabReportRecord
     */
    public TmLabReportRecord() {
        super(TmLabReport.TM_LAB_REPORT);
    }

    /**
     * Create a detached, initialised TmLabReportRecord
     */
    public TmLabReportRecord(String reportId, String userId, Timestamp updTime, Integer reportScore, Integer reportTeacherStatus, Integer reportStudentStatus, Integer reportStatus) {
        super(TmLabReport.TM_LAB_REPORT);

        set(0, reportId);
        set(1, userId);
        set(2, updTime);
        set(3, reportScore);
        set(4, reportTeacherStatus);
        set(5, reportStudentStatus);
        set(6, reportStatus);
    }
}
