/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmMixType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMixTypeRecord extends UpdatableRecordImpl<TmMixTypeRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1025034436;

    /**
     * Setter for <code>magmLab.TM_MIX_TYPE.MIX_ID</code>.
     */
    public void setMixId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_MIX_TYPE.MIX_ID</code>.
     */
    public String getMixId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_MIX_TYPE.MIX_NAME</code>.
     */
    public void setMixName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_MIX_TYPE.MIX_NAME</code>.
     */
    public String getMixName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_MIX_TYPE.MIX_MEMO</code>.
     */
    public void setMixMemo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_MIX_TYPE.MIX_MEMO</code>.
     */
    public String getMixMemo() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmMixType.TM_MIX_TYPE.MIX_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmMixType.TM_MIX_TYPE.MIX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmMixType.TM_MIX_TYPE.MIX_MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMixId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMixName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMixMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMixId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMixName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMixMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMixTypeRecord value1(String value) {
        setMixId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMixTypeRecord value2(String value) {
        setMixName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMixTypeRecord value3(String value) {
        setMixMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMixTypeRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmMixTypeRecord
     */
    public TmMixTypeRecord() {
        super(TmMixType.TM_MIX_TYPE);
    }

    /**
     * Create a detached, initialised TmMixTypeRecord
     */
    public TmMixTypeRecord(String mixId, String mixName, String mixMemo) {
        super(TmMixType.TM_MIX_TYPE);

        set(0, mixId);
        set(1, mixName);
        set(2, mixMemo);
    }
}
