/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao.tables.records;


import com.jlu.magmalab.dao.tables.TmStdValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmStdValueRecord extends UpdatableRecordImpl<TmStdValueRecord> implements Record3<String, String, Double> {

    private static final long serialVersionUID = -289888333;

    /**
     * Setter for <code>magmLab.TM_STD_VALUE.ELE_NAME</code>.
     */
    public void setEleName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>magmLab.TM_STD_VALUE.ELE_NAME</code>.
     */
    public String getEleName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>magmLab.TM_STD_VALUE.STD_ID</code>.
     */
    public void setStdId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magmLab.TM_STD_VALUE.STD_ID</code>.
     */
    public String getStdId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magmLab.TM_STD_VALUE.STD_VALUE</code>.
     */
    public void setStdValue(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>magmLab.TM_STD_VALUE.STD_VALUE</code>.
     */
    public Double getStdValue() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmStdValue.TM_STD_VALUE.ELE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmStdValue.TM_STD_VALUE.STD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return TmStdValue.TM_STD_VALUE.STD_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getStdValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getStdValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmStdValueRecord value1(String value) {
        setEleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmStdValueRecord value2(String value) {
        setStdId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmStdValueRecord value3(Double value) {
        setStdValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmStdValueRecord values(String value1, String value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmStdValueRecord
     */
    public TmStdValueRecord() {
        super(TmStdValue.TM_STD_VALUE);
    }

    /**
     * Create a detached, initialised TmStdValueRecord
     */
    public TmStdValueRecord(String eleName, String stdId, Double stdValue) {
        super(TmStdValue.TM_STD_VALUE);

        set(0, eleName);
        set(1, stdId);
        set(2, stdValue);
    }
}
